// frontend-angular/src/app/shared/components/product-cover.component.ts
// Porta de frontend/src/components/ProductCover.jsx.
import { Component, Input } from '@angular/core';
import { IconComponent } from './icon.component';
import { categoryIcon } from '../category-visual';

@Component({
  selector: 'app-product-cover',
  standalone: true,
  imports: [IconComponent],
  template: `
    @if (imageUrl) {
      <img class="mk-photo" [src]="imageUrl" [alt]="name" loading="lazy">
    } @else if (caption) {
      <div class="mk-ph">
        <app-icon [name]="iconeCategoria" [size]="28"></app-icon>
        <span>Sem fotografia</span>
      </div>
    } @else {
      <div class="mk-ph" role="img" aria-label="Sem fotografia">
        <app-icon [name]="iconeCategoria" [size]="28"></app-icon>
      </div>
    }
  `,
})
export class ProductCoverComponent {
  @Input() imageUrl?: string | null;
  @Input() category?: string | null;
  @Input() name = '';
  @Input() caption = true;

  get iconeCategoria(): string {
    return categoryIcon(this.category);
  }
}

// frontend/src/components/ProductCover.jsx
// src/components/ProductCover.jsx
// Capa de um produto: mostra a fotografia real carregada pelo fornecedor
// (imageUrl) ou, na sua ausência, um placeholder claro "Sem fotografia" — nunca
// uma imagem gerada que se faça passar por foto. As fotos são da
// responsabilidade do fornecedor (Catálogo → Carregar foto).
import { categoryVisual, Icon } from './icons';

export default function ProductCover({ imageUrl, category, name = '', caption = true }) {
  if (imageUrl) {
    return <img className="mk-photo" src={imageUrl} alt={name} loading="lazy" />;
  }
  const vis = categoryVisual(category);
  return (
    <div className="mk-ph" aria-label="Sem fotografia">
      <Icon name={vis.icon} size={28} />
      {caption ? <span>Sem fotografia</span> : null}
    </div>
  );
}
